# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

updateLogTauF <- function(data1, data2, tauVec, alphaMtx1, alphaMtx2, bVec, J, K) {
    .Call(`_BREMSC_updateLogTauF`, data1, data2, tauVec, alphaMtx1, alphaMtx2, bVec, J, K)
}

updateZmtx <- function(taufMtxLog, J, K) {
    .Call(`_BREMSC_updateZmtx`, taufMtxLog, J, K)
}

updateNjVec <- function(zMtx) {
    .Call(`_BREMSC_updateNjVec`, zMtx)
}

updateTauVec <- function(njVec, K) {
    .Call(`_BREMSC_updateTauVec`, njVec, K)
}

getLogL <- function(zMtx, taufMtxLog, bVec, sigmaB) {
    .Call(`_BREMSC_getLogL`, zMtx, taufMtxLog, bVec, sigmaB)
}

updateAlphaMtxOne <- function(data0, z, alphaMtx, sd_alpha, bVec, K, P) {
    .Call(`_BREMSC_updateAlphaMtxOne`, data0, z, alphaMtx, sd_alpha, bVec, K, P)
}

updateBMtxOne <- function(data1, data2, z, tauVec, alphaMtx1, alphaMtx2, sdB, bVec, sigmaB, J, K) {
    .Call(`_BREMSC_updateBMtxOne`, data1, data2, z, tauVec, alphaMtx1, alphaMtx2, sdB, bVec, sigmaB, J, K)
}

